FROM node:22-alpine AS builder
RUN apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@9.15.4 --activate
WORKDIR /server
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm build

FROM node:22-alpine
RUN apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@9.15.4 --activate
WORKDIR /server
COPY --from=builder /server/.medusa/server ./
RUN pnpm install --prod --no-frozen-lockfile
ENV NODE_ENV=production
EXPOSE 9000
CMD ["pnpm", "start"]
